import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import App from "./App";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Project Capstone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://unpkg.com/@phosphor-icons/web@2.1.1"
          strategy="afterInteractive"
        />
      </head>

      <body
        className={`${poppins.className} flex w-screen bg-dark-2 text-white antialiased xl:h-screen`}
      >
        <App>{children}</App>
      </body>
    </html>
  );
}
